#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import glob
import os

from greens.reader import Reader

from moments.utils import read_tensor_moment_info_file

from obspy.core.trace import Trace
from obspy.core.stream import Stream

import math
import numpy as np


def calc_station(folder, name, component, moments):
    """Calculate station seismogram for given moments and green's
    functions (and their derivatives)

    Args:
        folder (str): folder that contains green's functions
        name (str): station name
        component (str): component to calculate (r, t, z)
        moments (dict): moments info object

    Returns:
        obspy.core.stream.Stream: obspy stream that contains the calculated
                                  seismogram
    """
    r = Reader(folder, name)

    data = None
    c = 'xyz'
    for m in range(3):
        for n in range(3):
            if m+n <= 2:
                # FIXME: divide by 10^15 dyne/cm^2 ?
                co = (1.0)/(math.factorial(m)*math.factorial(n))/1e15
                for i in range(3):
                    f = moments[(m, n)][i]
                    if m == 0:
                        grn = "dt^{t} G_{n}{i}"
                        st = r.get(grn.format(t=n, n=component, i=c[i]))
                        tr = st[0]
                        if data is None:
                            data = Trace(co*f*tr.data, tr.stats)
                        else:
                            data.data = data.data + co*f*tr.data
                    elif m == 1:
                        for j1 in range(3):
                            grn = "dt^{t} G_{n}{i},{j1}"
                            st = r.get(grn.format(t=n, n=component,
                                                  i=c[i], j1=c[j1]))
                            tr = st[0]
                            data.data = data.data + co*f[j1]*tr.data
                    else:  # m == 2
                        for j1 in range(3):
                            for j2 in range(3):
                                grn = "dt^{t} G_{n}{i},{j1}{j2}"
                                st = r.get(grn.format(t=n,
                                                      n=component,
                                                      i=c[i],
                                                      j1=c[j1],
                                                      j2=c[j2]))
                                tr = st[0]
                                data.data = data.data + co*f[j1][j2]*tr.data

    stream = Stream(traces=[data])
    return stream


def write_stream_as_sac(stream, folder, filename, verbose=False):
    """Writes stream as a sac file

    Args:
        stream (obspy.core.stream.Stream): stream object
        folder (str): folder to store the file
        filename (str): file name
        verbose (bool): print what you did
    """
    stream.write(os.path.join(folder, filename), 'SAC')
    if verbose:
        print(os.path.join(folder, filename) + " is written.")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Calculate seismograms from moments and Green\'s functions')
    parser.add_argument("momentfile", help="moment file")
    parser.add_argument("greens_path",
                        help="folder that contains green's functions")
    parser.add_argument("station_names", nargs="*",
                        help="station name (assumes all stations if omitted)")
    parser.add_argument("-o", "--output-folder",
                        help="output folder for seismograms (./seismograms)",
                        default="seismograms")
    parser.add_argument('-c', '--components', nargs='*',
                        default=['r', 't', 'z'],
                        help='components to calculate default r, t, z')
    parser.add_argument('-v', '--verbose', action='store_true')
    args = parser.parse_args()

    # read moment information file
    moments = read_tensor_moment_info_file(args.momentfile)

    if not args.station_names:  # if no station name is given
        folders = glob.glob(os.path.join(args.greens_path, '*_greens'))
        names = [folder.split('/')[-1].split('_')[0] for folder in folders]
        args.station_names = names

    # calculate seismogram and write it as a sac file
    for station_name in args.station_names:
        for component in args.components:
            st = calc_station(args.greens_path,
                              station_name, component, moments)
            write_stream_as_sac(st, args.output_folder,
                                station_name+'.'+component,
                                args.verbose)
