#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
from collections import defaultdict
import numpy as np
from numpy import cos, sin
import re

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

from moments.utils import crange
from moments.utils import write_vector_moment_info_file
from moments.calculators import VectorMomentCalc


def calc_force_vector(strike, dip):
    """Calculate force vector from `strike` and `dip`.

    Args:
        strike (float): strike in degrees
        dip (float): dip in degrees

    Returns:
        numpy.ndarray: force vector
    """

    phi = np.radians(strike)
    sigma = np.radians(dip)

    return np.array([cos(phi), sin(phi), sin(sigma)])


def get_slip_rate_function(rise, fall, rupt_time=0):
    """Returns the slip rate function from given rise and fall times.
    rupt_time delays the function for given amount
    Ji et al. 2003

    Args:
        rise (float): rise time
        fall (float): fall time
        rupt_time (float): rupture start time (shifts function through time)

    Returns:
        function: slip rate function
    """
    ts = rise
    te = fall
    t0 = rupt_time

    def slip_rate_function(t):
        t = t - t0
        c = 1.0/(ts+te)
        if 0 <= t <= ts:
            return c*(1-np.cos((np.pi*t)/ts))
        elif ts < t <= ts + te:
            return c*(1+np.cos((np.pi*(t-ts))/te))
        else:
            return 0
    return slip_rate_function


class Point(object):
    def __init__(self, match, mu):
        """Stores parameters for a point and from those it can calculate
        force vector for a given time.

        Args:
            match (match): regular expression match for a file line
            mu (dict): rigidity value contaning dict (dyne/cm^2)
        """
        self.x = float(match.group('x'))
        self.y = float(match.group('y'))
        self.depth = float(match.group('depth'))
        self.dist = float(match.group('dist'))
        self.slip = float(match.group('slip'))
        self.rake = float(match.group('rake'))
        self.rupt_time = float(match.group('rupt_time'))
        self.rise = float(match.group('rise'))
        self.fall = float(match.group('fall'))
        self.strike = float(match.group('strike'))
        self.dip = float(match.group('dip'))
        self.mu = mu[self.depth]
        self.force = None
        self.slip_rate_func = get_slip_rate_function(self.rise, self.fall,
                                                     self.rupt_time)

    def get_force(self, recalc=False):
        """Calculates and returns the force vector

        Args:
            recalc (bool): recalculate even if it is done before

        Returns:
            numpy.ndarray: force vector
        """
        if self.force is not None and not recalc:
            return self.force
        f = calc_force_vector(self.strike, self.dip)

        self.force = self.slip*f

        return self.force

    def get_force_at(self, t):
        """Returns force vector at a specific time

        Args:
            t (float): time which moment tensor is calculated

        Returns:
            numpy.ndarray: force vector
        """
        return self.slip_rate_func(t)*self.get_force()


def readfile(filename, mu):
    """Parses the file and returns `Point` list

    Args:
        filename (str): filename to parse
        mu (dict): rigidity values (dyne/cm^2)

    Returns:
       list: Point list
    """
    # parse header using regular expressions
    event_info = re.compile("#evx\s+(?P<evx>[\d\.]+) evy\s+(?P<evy>[\d\.]+) hypodepth\s+(?P<evdepth>[\d\.]+)")
    file_header = re.compile('#Total number of fault_segments=\s+(?P<segments>\d+)')
    segment_header = re.compile('#Fault_segment =\s+(?P<seg_id>\d+) nx\(Along\-strike\)=\s+(?P<nx>\d+) Dx=\s+(?P<dx>[\d\.]+)km ny\(downdip\)=\s+(?P<ny>\d+) Dy=\s+(?P<dy>[\d\.]+)km')

    point = re.compile('\s*(?P<x>[\-\d\.]+)\s+(?P<y>[\-\d\.]+)\s+(?P<depth>[\d\.]+)\s+(?P<dist>[\d\.]+)\s+(?P<slip>[\d\.]+)\s+(?P<rake>[\d\.]+)\s+(?P<rupt_time>[\d\.]+)\s+(?P<rise>[\d\.]+)\s+(?P<fall>[\d\.]+)\s+(?P<strike>[\d\.]+)\s+(?P<dip>[\d\.]+)')
    with open(filename) as f:
        event = event_info.match(f.readline())
        ev_x = float(event.group('evx'))
        ev_y = float(event.group('evy'))

        # ev_utm = utm.from_latlon(evla, evlo)
        # ev_x = ev_utm[1]  # northing
        # ev_y = ev_utm[0]  # easting

        header = file_header.match(f.readline())
        no_of_segments = int(header.group('segments'))

        total_n_p = 0  # total number of points

        for segment_id in range(no_of_segments):
            # read segment
            segment = segment_header.match(f.readline())
            # print("segment:", segment.groups())
            nx = int(segment.group('nx'))
            ny = int(segment.group('ny'))
            dx = float(segment.group('dx'))
            dy = float(segment.group('dy'))

            n_p = nx*ny

            # f.readline()  # Boundary of fault_segment ...
            # f.readline()  # Lon. Lat. Depth

            # # read boundaries
            # for i in range(5):
            #     boundary.match(f.readline())

            f.readline()  # Lon. Lat. depth dist...

            # read `n_p` points
            points = [Point(point.match(f.readline()), mu)
                      for i in range(n_p)]

            total_n_p += n_p

    # Convert lat, lon to xy coordinate using utm
    xyz = np.zeros((total_n_p, 3))
    for j in range(ny):
        for i in range(nx):
            p = points[i+j*nx]
            xyz[i+j*nx] = [p.x-ev_x, p.y-ev_y, p.depth]
    return (xyz, points, dx, dy)


def plot_points(xyz, points):
    """Plots the points in xyz space"""
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter([p[0] for p in xyz],
               [p[1] for p in xyz],
               [p[2] for p in xyz])
    ax.invert_zaxis()
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.show()


def generate_time_space_points(points, xyz, dt):
    """Generate time and space points to be used in moment calculation

    Args:
        points (list): Point list obtained from reading kinetic_out file
        xyz (numpy.ndarry): coordinates in xyz space
        dt (float): time interval

    Returns:
        tuple: (values, points, times)
    """
    # find max t
    maxt = max([point.rupt_time + point.rise + point.fall for point in points])
    times = crange(0, maxt, dt)
    values = []
    v_times = []
    v_points = []
    for time in times:
        for point, loc in zip(points, xyz):
            values.append(point.get_force_at(time))
            v_times.append(time)
            v_points.append(loc)
    return (np.array(values), np.array(v_points), np.array(v_times))


def read_rigidity_file(filename):
    """Read rigidity file and return values as a dict

    Args:
        filename: file to contain rigidity information

    Returns:
        dict: rigidity values
    """
    values = {}
    with open(filename) as f:
        lines = f.readlines()

    for line in lines:
        depth, value = [float(v) for v in line.split()]
        values[depth] = value

    return values

def deneme(self, values):
    pass



if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Parses kinetic_out file and calculates moment values")
    parser.add_argument("filename", help="file to parse")
    parser.add_argument("output", help="file to write moment info")
    parser.add_argument("--plot", help="plot the fault file in xyz space",
                        action="store_true")
    parser.add_argument("--dt", '-d', help="time interval (default is 0.1)",
                        default=0.1, type=float)
    parser.add_argument("--rigidity", '-m',
                        help="rigidity value (default is 3x10^11 dyne/cm^2)",
                        default=3e11, type=float)
    parser.add_argument("--rigidities", "-r",
                        help="read a file containing rigidity info for depth",
                        type=str)
    args = parser.parse_args()

    # If rigidity file is provided, use that, otherwise use one value
    # Using defaultdict to be consistent with data structure
    # This will give same value for any depth.
    rigidity = defaultdict(lambda: args.rigidity)
    if args.rigidities:
        rigidity = read_rigidity_file(args.rigidities)

    xyz, points, dx, dy = readfile(args.filename, rigidity)

    if args.plot:
        plot_points(xyz, points)

    v, p, t = generate_time_space_points(points, xyz, args.dt)

    calc = VectorMomentCalc(v, p, t, [dx, dy, 1], args.dt)
    write_vector_moment_info_file(calc, args.output)
